version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m -server"
      - "ES_HEAP_SIZE=128m"
      - "MAX_LOCKED_MEMORY=100000"
      - "elasticdata:/opt/elasticsearch/volatile/data"
      - "elasticlogs:/opt/elasticsearch/volatile/logs"
    ports:
      - 9200:9200

  logstash:
    build: .
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
