version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  logstash:
    build: .
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
